<a href="https://colab.research.google.com/github/blackcode-creator/Preprocessing_data_techniques/blob/main/preprocessing_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
#this is preprocessing data before training the model to use correct format of data
import numpy as np
from sklearn import preprocessing

In [3]:
input_data = np.array(
    [
     [5.1, -2.9, 3.3],
     [-1.2, 7.8, -6.1],
     [7.3, -9.9, -4.5]
    ]
)

In [4]:
#check the input data
print(input_data)


#There are several technique of processing data in various different 
# 1. Binarization
# 2. Mean Removal 
# 3. Scaling
# 4. Normalization

[[ 5.1 -2.9  3.3]
 [-1.2  7.8 -6.1]
 [ 7.3 -9.9 -4.5]]


In [5]:
#Binarization Technique
# Process of converting numerical values to boolean values
# We will use 2.1 as the threshold value
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)

print("\nBinarized data:\n", data_binarized)
#Output the convert from numerical values to binary values


Binarized data:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [7]:
#2. Mean Removal 
#process of removing the mean from the feature vector so each feature is centered to zero

print("\n Before:")
print("mean =", input_data.mean(axis=0))
print("std deviation =", input_data.std(axis=0))


 Before:
mean = [ 3.73333333 -1.66666667 -2.43333333]
std deviation = [3.60215985 7.27843084 4.10636363]


In [9]:
#Removing the mean
data_scaled = preprocessing.scale(input_data)
print("\n After: \n")
print("Mean = ", data_scaled.mean(axis=0))
print("std deviation = ", data_scaled.std(axis=0))

#the mean value will be very closed to 0 and standard deviation is 1.


 After: 

Mean =  [ 7.40148683e-17 -7.40148683e-17 -3.70074342e-17]
std deviation =  [1. 1. 1.]


In [10]:
#Scaling Technique
#each value of each feature will be varying between many random values.

#min max scaling 
data_scalar_minmax = preprocessing.MinMaxScaler(feature_range =(0, 1))
data_scaled_minmax = data_scalar_minmax.fit_transform(input_data)
print("\nMin Max scaled data:\n", data_scaled_minmax)


Min Max scaled data:
 [[0.74117647 0.39548023 1.        ]
 [0.         1.         0.        ]
 [1.         0.         0.17021277]]


In [11]:
#Normalization Technique
#modifying the values in the vectors to measure them on a common scale

#Normalize data
data_normalized_l1 = preprocessing.normalize(input_data, norm ="l1")
data_normalized_l2 = preprocessing.normalize(input_data,norm="l2")

print("\nL1 normalized data:\n", data_normalized_l1)
print("\nL2 normalized data:\n", data_normalized_l2)


L1 normalized data:
 [[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.33640553 -0.4562212  -0.20737327]]

L2 normalized data:
 [[ 0.75765788 -0.43082507  0.49024922]
 [-0.12030718  0.78199664 -0.61156148]
 [ 0.55734935 -0.75585734 -0.34357152]]
